### ISSUE TITLE
a mistake in refs.bib

### ISSUE THREAD

**Issue by spongebobsquare** [yyeboah/Awesome-Text-to-3D#9]
Thanks for your hard work. It helped me a lot. There is just a little mistake, as in the picture below↓.
The titlel here actually is **One-shot Implicit Animatable Avatars with Model-based Priors**
![image](https://github.com/yyeboah/Awesome-Text-to-3D/assets/59282845/d8ae4972-0476-459a-bfa9-584a1aab4e07)

**Comment by yyeboah** [comment]
Thanks for reporting this and glad you've found this project useful.
